#!/bin/bash
# GitHub Device Flow auth completion script
# Generated by B#501 (s1679) for wq-764
#
# After human visits https://github.com/login/device and enters the code,
# this script polls for the token, adds the SSH key, and switches to SSH remote.
#
# Usage: ./complete-github-auth.sh <device_code>

DEVICE_CODE="$1"
CLIENT_ID="178c6fc778ccc68e1d6a"
SSH_KEY_FILE="$HOME/.ssh/id_ed25519.pub"
REPO_DIR="$HOME/moltbook-mcp"

if [ -z "$DEVICE_CODE" ]; then
    echo "Usage: $0 <device_code>"
    exit 1
fi

echo "Polling GitHub for authorization..."
echo "(Waiting for human to visit https://github.com/login/device)"
echo ""

# Poll every 5 seconds (GitHub's specified interval)
MAX_ATTEMPTS=180  # 15 minutes
ATTEMPT=0

while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
    RESPONSE=$(curl -s -X POST https://github.com/login/oauth/access_token \
        -H "Accept: application/json" \
        -d "client_id=$CLIENT_ID&device_code=$DEVICE_CODE&grant_type=urn:ietf:params:oauth:grant-type:device_code")

    ERROR=$(echo "$RESPONSE" | jq -r '.error // empty')
    TOKEN=$(echo "$RESPONSE" | jq -r '.access_token // empty')

    if [ -n "$TOKEN" ] && [ "$TOKEN" != "null" ]; then
        echo "Authorization received!"
        echo ""

        # Step 1: Add SSH key to GitHub
        echo "Adding SSH key to GitHub..."
        SSH_KEY=$(cat "$SSH_KEY_FILE")
        ADD_RESULT=$(curl -s -w "\n%{http_code}" -X POST https://api.github.com/user/keys \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"title\":\"moltbot@terminalcraft.xyz (auto-added s1679)\",\"key\":\"$SSH_KEY\"}")

        HTTP_CODE=$(echo "$ADD_RESULT" | tail -1)
        BODY=$(echo "$ADD_RESULT" | head -n -1)

        if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "422" ]; then
            if [ "$HTTP_CODE" = "422" ]; then
                echo "SSH key already exists on GitHub (that's fine)."
            else
                echo "SSH key added to GitHub successfully!"
            fi

            # Step 2: Update gh CLI config with new token
            echo ""
            echo "Updating gh CLI auth..."
            echo "$TOKEN" | gh auth login --with-token 2>/dev/null

            # Step 3: Switch remote to SSH
            echo ""
            echo "Switching remote to SSH..."
            cd "$REPO_DIR"
            git remote set-url origin git@github.com:terminalcraft/moltbook-mcp.git

            # Step 4: Test SSH connection
            echo ""
            echo "Testing SSH connection..."
            ssh -T git@github.com 2>&1 || true

            # Step 5: Test git fetch
            echo ""
            echo "Testing git fetch..."
            git fetch origin 2>&1

            echo ""
            echo "=== SETUP COMPLETE ==="
            echo "Remote: $(git remote get-url origin)"
            echo "gh auth: $(gh auth status 2>&1 | head -2)"
            exit 0
        else
            echo "Failed to add SSH key (HTTP $HTTP_CODE):"
            echo "$BODY" | jq -r '.message // .' 2>/dev/null || echo "$BODY"
            echo ""
            echo "Token was obtained. You can manually add the key:"
            echo "  cat $SSH_KEY_FILE"
            echo "Then switch remote:"
            echo "  cd $REPO_DIR && git remote set-url origin git@github.com:terminalcraft/moltbook-mcp.git"
            exit 1
        fi
    elif [ "$ERROR" = "authorization_pending" ]; then
        ATTEMPT=$((ATTEMPT + 1))
        sleep 5
    elif [ "$ERROR" = "slow_down" ]; then
        ATTEMPT=$((ATTEMPT + 1))
        sleep 10
    elif [ "$ERROR" = "expired_token" ]; then
        echo "Device code expired. Re-run the auth flow."
        exit 1
    elif [ "$ERROR" = "access_denied" ]; then
        echo "Authorization denied by user."
        exit 1
    else
        echo "Unexpected response: $RESPONSE"
        exit 1
    fi
done

echo "Timed out waiting for authorization."
exit 1
