#!/bin/bash
# Domain setup script for moltbot.xyz (or whatever domain is purchased)
# Run this AFTER DNS A record points to this server's IP
# Usage: sudo bash setup-domain.sh moltbot.xyz

set -euo pipefail

DOMAIN="${1:?Usage: setup-domain.sh <domain>}"
IP="terminalcraft.xyz"

echo "=== Setting up $DOMAIN ==="
echo "Ensure DNS A record for $DOMAIN points to $IP before running this."
echo ""

# Step 1: Create nginx config with reverse proxy to all services
cat > /etc/nginx/sites-available/"$DOMAIN" <<NGINX
# $DOMAIN - Moltbook MCP API gateway
# Auto-generated by setup-domain.sh

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Redirect everything else to HTTPS (after cert is obtained)
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    # SSL certs (will be created by certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Main API (port 3847)
    location / {
        proxy_pass http://127.0.0.1:3847;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    # Verify server (port 3848)
    location /verify/ {
        proxy_pass http://127.0.0.1:3848/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX

# Step 2: Enable the site
ln -sf /etc/nginx/sites-available/"$DOMAIN" /etc/nginx/sites-enabled/"$DOMAIN"

# Step 3: Test nginx config (without SSL first — certs don't exist yet)
# Temporarily comment out the SSL server block for initial certbot run
cat > /etc/nginx/sites-available/"$DOMAIN"-temp <<NGINX_TEMP
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://127.0.0.1:3847;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_TEMP

# Use temp config for certbot
ln -sf /etc/nginx/sites-available/"$DOMAIN"-temp /etc/nginx/sites-enabled/"$DOMAIN"
nginx -t && systemctl reload nginx

echo ""
echo "=== Step 3: Obtaining SSL certificate ==="
certbot certonly --webroot -w /var/www/html -d "$DOMAIN" --non-interactive --agree-tos --email "terminalcraft@proton.me"

# Step 4: Switch to full SSL config
ln -sf /etc/nginx/sites-available/"$DOMAIN" /etc/nginx/sites-enabled/"$DOMAIN"
rm -f /etc/nginx/sites-available/"$DOMAIN"-temp
nginx -t && systemctl reload nginx

echo ""
echo "=== Step 5: Setting up auto-renewal ==="
# certbot auto-renewal is usually already set up via systemd timer
systemctl enable certbot.timer 2>/dev/null || true
systemctl start certbot.timer 2>/dev/null || true

echo ""
echo "=== Done! ==="
echo "Your API is now available at https://$DOMAIN"
echo "  - Main API: https://$DOMAIN/"
echo "  - agent.json: https://$DOMAIN/agent.json"
echo "  - Status: https://$DOMAIN/status/dashboard"
echo "  - Knowledge: https://$DOMAIN/knowledge/patterns"
echo "  - Verify: https://$DOMAIN/verify/"
echo ""
echo "Next steps:"
echo "  1. Update ~/moltbook-mcp/api.mjs to reference https://$DOMAIN in agent.json"
echo "  2. Update BRIEFING.md exchange protocol URL"
echo "  3. Commit and push changes"
