#!/usr/bin/env node
// agora.test.mjs — Tests for agora.js component
// Generated by generate-test-scaffold.mjs (wq-159)
// Run with: node --test components/agora.test.mjs

import { test, describe, before, after, mock } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'fs';
import { join } from 'path';

// Set up isolated test environment
const TEST_HOME = '/tmp/agora-test-' + Date.now();
const TEST_STATE_DIR = join(TEST_HOME, '.config/moltbook');
process.env.HOME = TEST_HOME;
mkdirSync(TEST_STATE_DIR, { recursive: true });

// Mock server that captures tool registrations
function createMockServer() {
  const tools = {};
  return {
    tool: (name, description, schema, handler) => {
      tools[name] = { description, schema, handler };
    },
    getTools: () => tools,
    callTool: async (name, args) => {
      if (!tools[name]) throw new Error(`Tool ${name} not found`);
      return tools[name].handler(args);
    }
  };
}

// Extract text from tool result
function getText(result) {
  return result?.content?.[0]?.text || '';
}

describe('agora.js component', () => {
  let server;

  before(async () => {
    const mod = await import('./agora.js');
    server = createMockServer();
    mod.register(server, { sessionNum: 100, sessionType: 'B' });
  });

  after(() => {
    mock.reset();
  });

  describe('tool registration', () => {
    test('registers all expected tools', () => {
      const tools = server.getTools();
      const expectedTools = [
    "agora_markets",
    "agora_market_detail",
    "agora_register",
    "agora_trade",
    "agora_leaderboard",
    "agora_stats",
    "agora_positions",
    "agora_create_market"
];

      for (const toolName of expectedTools) {
        assert.ok(tools[toolName], `Tool ${toolName} should be registered`);
      }
    });
  });

  // Tool functionality tests - auto-generated with example parameters
  describe('tool functionality', () => {
    test('agora_markets returns expected structure (params: category, limit)', async () => {
      const result = await server.callTool('agora_markets', { category: 'test-category', limit: 1 });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('agora_market_detail returns expected structure (params: market_id)', async () => {
      const result = await server.callTool('agora_market_detail', { market_id: 'test-market_id' });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('agora_register returns expected structure (params: handle)', async () => {
      const result = await server.callTool('agora_register', { handle: 'test-handle' });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('agora_trade returns expected structure (params: market_id, amount)', async () => {
      const result = await server.callTool('agora_trade', { market_id: 'test-market_id', amount: 1 });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('agora_leaderboard returns expected structure (params: limit)', async () => {
      const result = await server.callTool('agora_leaderboard', { limit: 1 });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('agora_stats returns expected structure', async () => {
      const result = await server.callTool('agora_stats', {});
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('agora_positions returns expected structure', async () => {
      const result = await server.callTool('agora_positions', {});
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('agora_create_market returns expected structure (params: question, category)', async () => {
      const result = await server.callTool('agora_create_market', {
        question: 'Will agents achieve full autonomy by 2027?',
        category: 'ai'
      });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('agora_create_market without credentials returns registration prompt', async () => {
      // The test env has no credentials file, so it should prompt to register
      const result = await server.callTool('agora_create_market', {
        question: 'Test market question for coverage',
        category: 'meta'
      });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
      // Without valid credentials, expect either registration prompt or API error
      assert.ok(
        text.includes('register') || text.includes('error') || text.includes('failed') || text.includes('Market created'),
        'Should indicate auth issue or succeed'
      );
    });
  });
});
