#!/usr/bin/env node
// aicq.test.mjs — Tests for aicq.js component
// Generated by generate-test-scaffold.mjs (wq-159)
// Run with: node --test components/aicq.test.mjs

import { test, describe, before, after, mock } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'fs';
import { join } from 'path';

// Set up isolated test environment
const TEST_HOME = '/tmp/aicq-test-' + Date.now();
const TEST_STATE_DIR = join(TEST_HOME, '.config/moltbook');
process.env.HOME = TEST_HOME;
mkdirSync(TEST_STATE_DIR, { recursive: true });

// Mock server that captures tool registrations
function createMockServer() {
  const tools = {};
  return {
    tool: (name, description, schema, handler) => {
      tools[name] = { description, schema, handler };
    },
    getTools: () => tools,
    callTool: async (name, args) => {
      if (!tools[name]) throw new Error(`Tool ${name} not found`);
      return tools[name].handler(args);
    }
  };
}

// Extract text from tool result
function getText(result) {
  return result?.content?.[0]?.text || '';
}

describe('aicq.js component', () => {
  let server;

  before(async () => {
    const mod = await import('./aicq.js');
    server = createMockServer();
    mod.register(server, { sessionNum: 100, sessionType: 'B' });
  });

  after(() => {
    mock.reset();
  });

  describe('tool registration', () => {
    test('registers all expected tools', () => {
      const tools = server.getTools();
      const expectedTools = [
    "aicq_heartbeat",
    "aicq_send",
    "aicq_search"
];

      for (const toolName of expectedTools) {
        assert.ok(tools[toolName], `Tool ${toolName} should be registered`);
      }
    });
  });

  // Tool functionality tests - auto-generated with example parameters
  describe('tool functionality', () => {
    test('aicq_heartbeat returns expected structure (params: since_id)', async () => {
      const result = await server.callTool('aicq_heartbeat', { since_id: 1 });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('aicq_send returns expected structure (params: content)', async () => {
      const result = await server.callTool('aicq_send', { content: 'test-content' });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('aicq_search returns expected structure (params: query, limit)', async () => {
      const result = await server.callTool('aicq_search', { query: 'test-query', limit: 1 });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });
  });
});
