#!/usr/bin/env node
// moltgram.test.mjs — Tests for moltgram.js component
// Generated by generate-test-scaffold.mjs (wq-159)
// Run with: node --test components/moltgram.test.mjs

import { test, describe, before, after, mock } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'fs';
import { join } from 'path';

// Set up isolated test environment
const TEST_HOME = '/tmp/moltgram-test-' + Date.now();
const TEST_STATE_DIR = join(TEST_HOME, '.config/moltbook');
process.env.HOME = TEST_HOME;
mkdirSync(TEST_STATE_DIR, { recursive: true });

// Mock server that captures tool registrations
function createMockServer() {
  const tools = {};
  return {
    tool: (name, description, schema, handler) => {
      tools[name] = { description, schema, handler };
    },
    getTools: () => tools,
    callTool: async (name, args) => {
      if (!tools[name]) throw new Error(`Tool ${name} not found`);
      return tools[name].handler(args);
    }
  };
}

// Extract text from tool result
function getText(result) {
  return result?.content?.[0]?.text || '';
}

describe('moltgram.js component', () => {
  let server;

  before(async () => {
    const mod = await import('./moltgram.js');
    server = createMockServer();
    mod.default(server);
  });

  after(() => {
    mock.reset();
  });

  describe('tool registration', () => {
    test('registers all expected tools', () => {
      const tools = server.getTools();
      const expectedTools = [
    "moltgram_register",
    "moltgram_posts",
    "moltgram_fame",
    "moltgram_post",
    "moltgram_claw",
    "moltgram_comment",
    "moltgram_strategy",
    "moltgram_craft"
];

      for (const toolName of expectedTools) {
        assert.ok(tools[toolName], `Tool ${toolName} should be registered`);
      }
    });
  });

  // Tool functionality tests — API calls fail gracefully since no real server
  describe('tool functionality', () => {
    test('moltgram_register handles API failure gracefully', async () => {
      const result = await server.callTool('moltgram_register', { name: 'test-agent' });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
      assert.ok(text.includes('failed') || text.includes('Registered'), 'Should indicate success or failure');
    });

    test('moltgram_posts handles API failure gracefully', async () => {
      const result = await server.callTool('moltgram_posts', { sort_by: 'top' });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('moltgram_fame handles API failure gracefully', async () => {
      const result = await server.callTool('moltgram_fame', {});
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('moltgram_post requires token', async () => {
      const result = await server.callTool('moltgram_post', {
        image_url: 'https://example.com/img.png',
        caption: 'test caption'
      });
      const text = getText(result);
      assert.ok(text.includes('Not registered'), 'Should require registration first');
    });

    test('moltgram_claw requires token', async () => {
      const result = await server.callTool('moltgram_claw', { post_id: 'test-id' });
      const text = getText(result);
      assert.ok(text.includes('Not registered'), 'Should require registration first');
    });

    test('moltgram_comment requires token', async () => {
      const result = await server.callTool('moltgram_comment', { post_id: 'test-id', text: 'hello' });
      const text = getText(result);
      assert.ok(text.includes('Not registered'), 'Should require registration first');
    });

    test('moltgram_strategy returns strategy report', async () => {
      const result = await server.callTool('moltgram_strategy', {});
      const text = getText(result);
      assert.ok(text.includes('Strategy Report') || text.includes('failed'), 'Should contain strategy data or graceful failure');
    });

    test('moltgram_craft returns post recommendation', async () => {
      const result = await server.callTool('moltgram_craft', { path: 'auto' });
      const text = getText(result);
      assert.ok(text.includes('Post Recommendation') || text.includes('failed'), 'Should contain recommendation or graceful failure');
    });

    test('moltgram_craft respects theme parameter', async () => {
      const result = await server.callTool('moltgram_craft', { theme: 'infrastructure', path: 'claws' });
      const text = getText(result);
      assert.ok(text.includes('infrastructure') || text.includes('failed'), 'Should incorporate theme or fail gracefully');
    });

    test('moltgram_craft supports comments path', async () => {
      const result = await server.callTool('moltgram_craft', { path: 'comments' });
      const text = getText(result);
      assert.ok(text.includes('comments') || text.includes('discussion') || text.includes('failed'), 'Should provide comments-path advice');
    });
  });
});
