#!/usr/bin/env node
// moltchan.test.mjs — Tests for moltchan.js component
// Generated by generate-test-scaffold.mjs (wq-159)
// Run with: node --test components/moltchan.test.mjs

import { test, describe, before, after, mock } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'fs';
import { join } from 'path';

// Set up isolated test environment
const TEST_HOME = '/tmp/moltchan-test-' + Date.now();
const TEST_STATE_DIR = join(TEST_HOME, '.config/moltbook');
process.env.HOME = TEST_HOME;
mkdirSync(TEST_STATE_DIR, { recursive: true });

// Mock server that captures tool registrations
function createMockServer() {
  const tools = {};
  return {
    tool: (name, description, schema, handler) => {
      tools[name] = { description, schema, handler };
    },
    getTools: () => tools,
    callTool: async (name, args) => {
      if (!tools[name]) throw new Error(`Tool ${name} not found`);
      return tools[name].handler(args);
    }
  };
}

// Extract text from tool result
function getText(result) {
  return result?.content?.[0]?.text || '';
}

describe('moltchan.js component', () => {
  let server;

  before(async () => {
    const mod = await import('./moltchan.js');
    server = createMockServer();
    mod.register(server, { sessionNum: 100, sessionType: 'B' });
  });

  after(() => {
    mock.reset();
  });

  describe('tool registration', () => {
    test('registers all expected tools', () => {
      const tools = server.getTools();
      const expectedTools = [
    "moltchan_boards",
    "moltchan_threads",
    "moltchan_thread",
    "moltchan_post",
    "moltchan_reply",
    "moltchan_search",
    "moltchan_me"
];

      for (const toolName of expectedTools) {
        assert.ok(tools[toolName], `Tool ${toolName} should be registered`);
      }
    });
  });

  // Tool functionality tests - auto-generated with example parameters
  describe('tool functionality', () => {
    test('moltchan_boards returns expected structure', async () => {
      const result = await server.callTool('moltchan_boards', {});
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('moltchan_threads returns expected structure (params: board, limit)', async () => {
      const result = await server.callTool('moltchan_threads', { board: 'test-board', limit: 1 });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('moltchan_thread returns expected structure (params: thread_id)', async () => {
      const result = await server.callTool('moltchan_thread', { thread_id: 'test-thread_id' });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('moltchan_post returns expected structure (params: board, title, content)', async () => {
      const result = await server.callTool('moltchan_post', { board: 'test-board', title: 'test-title', content: 'test-content' });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('moltchan_reply returns expected structure (params: thread_id, content)', async () => {
      const result = await server.callTool('moltchan_reply', { thread_id: 'test-thread_id', content: 'test-content' });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('moltchan_search returns expected structure (params: query, limit)', async () => {
      const result = await server.callTool('moltchan_search', { query: 'test-query', limit: 1 });
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });

    test('moltchan_me returns expected structure', async () => {
      const result = await server.callTool('moltchan_me', {});
      const text = getText(result);
      assert.ok(text, 'Should return text content');
    });
  });
});
