#!/usr/bin/env node
// prompt-inject.test.mjs — Tests for prompt-inject.js component
// Generated by generate-test-scaffold.mjs (wq-159), enhanced with fs mocking
// Run with: node --test components/prompt-inject.test.mjs

import { test, describe, before, after, beforeEach, mock } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync, readFileSync, rmSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Set up isolated test environment
const TEST_HOME = '/tmp/prompt-inject-test-' + Date.now();
const TEST_STATE_DIR = join(TEST_HOME, '.config/moltbook');
process.env.HOME = TEST_HOME;
mkdirSync(TEST_STATE_DIR, { recursive: true });

// Create a test prompt-inject.json in the moltbook-mcp directory
const __dirname = dirname(fileURLToPath(import.meta.url));
const TEST_MANIFEST_PATH = join(__dirname, '..', 'prompt-inject.test-temp.json');

// Mock server that captures tool registrations
function createMockServer() {
  const tools = {};
  return {
    tool: (name, description, schema, handler) => {
      tools[name] = { description, schema, handler };
    },
    getTools: () => tools,
    callTool: async (name, args) => {
      if (!tools[name]) throw new Error(`Tool ${name} not found`);
      return tools[name].handler(args);
    }
  };
}

// Extract text from tool result
function getText(result) {
  return result?.content?.[0]?.text || '';
}

// Helper to create test manifest
function writeTestManifest(data) {
  writeFileSync(TEST_MANIFEST_PATH, JSON.stringify(data, null, 2));
}

describe('prompt-inject.js component', () => {
  let server;
  let originalManifestPath;

  before(async () => {
    // We'll need to patch the module to use our test path
    // Since the module uses a hardcoded path, we'll test with the real manifest
    // but be careful to restore state
    const mod = await import('./prompt-inject.js');
    server = createMockServer();
    mod.register(server, { sessionNum: 100, sessionType: 'B' });
  });

  after(() => {
    mock.reset();
    // Clean up any test files
    try { rmSync(TEST_MANIFEST_PATH); } catch {}
  });

  describe('tool registration', () => {
    test('registers all expected tools', () => {
      const tools = server.getTools();
      const expectedTools = [
        "prompt_inject_list",
        "prompt_inject_add",
        "prompt_inject_update",
        "prompt_inject_remove",
        "prompt_inject_reorder"
      ];

      for (const toolName of expectedTools) {
        assert.ok(tools[toolName], `Tool ${toolName} should be registered`);
      }
    });
  });

  describe('prompt_inject_list', () => {
    test('lists injections from manifest', async () => {
      const result = await server.callTool('prompt_inject_list', {});
      const text = getText(result);

      // Should either show injections or indicate none configured
      assert.ok(text, 'Should return text content');
      assert.ok(
        text.includes('Prompt Injections') || text.includes('No prompt injections'),
        'Should indicate injection status'
      );
    });
  });

  describe('prompt_inject_add', () => {
    test('adds new injection successfully', async () => {
      const testFile = `test-inject-${Date.now()}.txt`;
      const result = await server.callTool('prompt_inject_add', {
        file: testFile,
        description: 'Test injection for unit tests',
        priority: 500,
        sessions: 'B'
      });
      const text = getText(result);

      assert.ok(text.includes('Added') || text.includes('already exists'), 'Should confirm addition or indicate exists');

      // Clean up - remove the test injection
      await server.callTool('prompt_inject_remove', { file: testFile });
    });

    test('rejects duplicate injection', async () => {
      const testFile = `test-dup-${Date.now()}.txt`;

      // Add first
      await server.callTool('prompt_inject_add', {
        file: testFile,
        description: 'First add',
        priority: 100
      });

      // Try to add again
      const result = await server.callTool('prompt_inject_add', {
        file: testFile,
        description: 'Duplicate',
        priority: 200
      });
      const text = getText(result);

      assert.ok(text.includes('already exists'), 'Should indicate duplicate');

      // Clean up
      await server.callTool('prompt_inject_remove', { file: testFile });
    });

    test('adds injection with requires dependency', async () => {
      const testFile = `test-dep-${Date.now()}.txt`;
      const result = await server.callTool('prompt_inject_add', {
        file: testFile,
        description: 'Injection with dependency',
        priority: 100,
        requires: 'other-inject.txt'
      });
      const text = getText(result);

      assert.ok(text.includes('Added'), 'Should confirm addition');
      assert.ok(text.includes('requires'), 'Should mention requires');

      // Clean up
      await server.callTool('prompt_inject_remove', { file: testFile });
    });
  });

  describe('prompt_inject_update', () => {
    test('updates existing injection', async () => {
      const testFile = `test-update-${Date.now()}.txt`;

      // Add first
      await server.callTool('prompt_inject_add', {
        file: testFile,
        description: 'Original description',
        priority: 100
      });

      // Update
      const result = await server.callTool('prompt_inject_update', {
        file: testFile,
        description: 'Updated description',
        priority: 50
      });
      const text = getText(result);

      assert.ok(text.includes('Updated') || text.includes('updated'), 'Should confirm update');
      assert.ok(text.includes('50'), 'Should show new priority');

      // Clean up
      await server.callTool('prompt_inject_remove', { file: testFile });
    });

    test('handles update of non-existent injection', async () => {
      const result = await server.callTool('prompt_inject_update', {
        file: 'nonexistent-file-12345.txt',
        description: 'Should fail'
      });
      const text = getText(result);

      assert.ok(text.includes('not found'), 'Should indicate not found');
    });

    test('removes requires dependency when set to null', async () => {
      const testFile = `test-null-req-${Date.now()}.txt`;

      // Add with requires
      await server.callTool('prompt_inject_add', {
        file: testFile,
        description: 'Has dependency',
        requires: 'dep.txt'
      });

      // Update to remove requires
      const result = await server.callTool('prompt_inject_update', {
        file: testFile,
        requires: null
      });
      const text = getText(result);

      assert.ok(text.includes('Updated'), 'Should confirm update');
      assert.ok(!text.includes('requires='), 'Should not show requires');

      // Clean up
      await server.callTool('prompt_inject_remove', { file: testFile });
    });
  });

  describe('prompt_inject_remove', () => {
    test('removes existing injection', async () => {
      const testFile = `test-remove-${Date.now()}.txt`;

      // Add first
      await server.callTool('prompt_inject_add', {
        file: testFile,
        description: 'To be removed'
      });

      // Remove
      const result = await server.callTool('prompt_inject_remove', { file: testFile });
      const text = getText(result);

      assert.ok(text.includes('Removed'), 'Should confirm removal');
      assert.ok(text.includes(testFile), 'Should include filename');
    });

    test('handles removal of non-existent injection', async () => {
      const result = await server.callTool('prompt_inject_remove', {
        file: 'nonexistent-file-67890.txt'
      });
      const text = getText(result);

      assert.ok(text.includes('not found'), 'Should indicate not found');
    });
  });

  describe('prompt_inject_reorder', () => {
    test('changes injection priority', async () => {
      const testFile = `test-reorder-${Date.now()}.txt`;

      // Add first
      await server.callTool('prompt_inject_add', {
        file: testFile,
        description: 'To be reordered',
        priority: 100
      });

      // Reorder
      const result = await server.callTool('prompt_inject_reorder', {
        file: testFile,
        new_priority: 25
      });
      const text = getText(result);

      assert.ok(text.includes('100') && text.includes('25'), 'Should show old and new priority');

      // Clean up
      await server.callTool('prompt_inject_remove', { file: testFile });
    });

    test('handles reorder of non-existent injection', async () => {
      const result = await server.callTool('prompt_inject_reorder', {
        file: 'nonexistent-reorder-12345.txt',
        new_priority: 50
      });
      const text = getText(result);

      assert.ok(text.includes('not found'), 'Should indicate not found');
    });
  });
});
